#!/usr/bin/env bash

# arg1: name of .dist file, generated by Nuitka
# arg2: app dir, directory where app bundle is stored

# Assumptions:
# * Info.plist is located in same directory as .dist bundle
# * app bundle has the same name as .dist bundle

# check on whether cp preserves or creates new file creation date.

# verify .dist file exists
# verify app directory exists
#    create if it doesn't
# stripe file name from .dist
# move existing file to old file - append date/time to end
# mkdir -p app-dir/app-name.app/Contents/MacOS
# mkdir app-name/Resources
# cp Info.plist app-dir/app-name.app
# cp -r Resources app-dir/app-name.app/Contents/Resources
# mv -r app-name.dist/* app-dir/app-name.app/Contents/MacOS

